var Buffer = require('buffer/').Buffer;

module.exports.open = function() {
    var open = "CQEAAAAAAAAAAAAA1AcAAAAAAABhZG1pbi4kY21kAAAAAAABAAAA4gAAABBpc01hc3RlcgABAAAAA2NsaWVudADHAAAAA2FwcGxpY2F0aW9uAB0AAAACbmFtZQAOAAAATW9uZ29EQiBTaGVsbAAAA2RyaXZlcgA6AAAAAm5hbWUAGAAAAE1vbmdvREIgSW50ZXJuYWwgQ2xpZW50AAJ2ZXJzaW9uAAYAAAAzLjQuNwAAA29zAFIAAAACdHlwZQAGAAAATGludXgAAm5hbWUABwAAAFVidW50dQACYXJjaGl0ZWN0dXJlAAcAAAB4ODZfNjQAAnZlcnNpb24ABgAAADE3LjEwAAAAAA==";
    return Buffer.from(open, "base64");
}